Update hehe

diff --git a/hehe b/hehe
--- a/hehe
+++ b/hehe
@@ -70,17 +70,17 @@ clear
     exit 0
 }
 
-send_code_telegram
+# send_code_telegram
 
 # Prompt the user to enter the verification code
-echo -n -e "\033[1;33m◇ ENTER VERIFICATION CODE: \033[0m"
-read user_code
+# echo -n -e "\033[1;33m◇ ENTER VERIFICATION CODE: \033[0m"
+# read user_code
 
 # Compare the entered code with the generated code
-if [[ "$user_code" != "$random_code" ]]; then
-    echo "Invalid code. Installation aborted."
-    exit 1
-fi
+# if [[ "$user_code" != "$random_code" ]]; then
+  #  echo "Invalid code. Installation aborted."
+  #  exit 1
+# fi
 
 # Variable Initialization
 _lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev)
